name: lab3

on:
  push:
    branches:
      - '**lab3**'
  pull_request:
    branches:
      - lab3

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

      fail-fast: false

    steps:

      - name: setup
        run: |
          echo "${HOME}/opt/conda/bin" >> $GITHUB_PATH
          echo $GITHUB_REPOSITORY
          echo $GITHUB_REF
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.head }}
          echo ${{ github.event.pull_request.user.login }}
          echo ${{ github.event.pull_request.head.user.login }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: dependency (ubuntu)
        if: matrix.os != 'macos-latest'
        run: |
          go version
          sudo apt install wget
          echo "wget"
          wget https://golang.org/dl/go1.17.1.linux-amd64.tar.gz
          echo "rm"
          rm -rf /usr/local/go
          echo "tar"
          tar -C /usr/local -xzf go1.17.1.linux-amd64.tar.gz
          echo "mv"
          sudo mv go /usr/local
          echo "export"
          export PATH=$PATH:/usr/local/go/bin
          go version
      - name: grade
        run: |
          username=$( [ -z "${{ github.event.pull_request.user.login }}" ] && echo $GITHUB_REPOSITORY | cut -d '/' -f 1 || echo ${{ github.event.pull_request.user.login }})
          echo "cd lab3/$username"
          cd lab3/$username
          bash ../validate.sh